apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      serviceAccountName: victoria-metrics
      containers:
      - name: vm
        image: victoriametrics/victoria-metrics:stable
        args:
          - '-retentionPeriod=2'
        ports:
        - containerPort: 8428
