apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  labels:
    app: victoria-metrics
spec:
  ports:
    - port: 8428
      targetPort: 8428
      protocol: TCP
      name: http
  selector:
    app: victoria-metrics
  type: ClusterIP
