apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
data:
  config.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.default.svc.cluster.local:9100']
