apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
data:
  config.yaml: |
    global:
      scrape_interval: 15s

  scrape_configs:
  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    static_configs:
      - targets: ['netdata.monitoring.svc.cluster.local:19999']
