apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager.monitoring.svc:9093']

    rule_files:
      - "../CRD/PrometheusRules/prometheus-alert-rules.yaml" 

    scrape_configs:
    - job_name: node
      static_configs:
      - targets: ['10.106.170.167:9100']