hostname: ${hostname}
ssh_pwauth: false

users:
  - default
  - name: user01
    primary_group: user01
    gecos: user01
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    passwd: ${user_passwd}
    ssh_authorized_keys:
      - ${ssh_public_key}

final_message: "Cloud-init has finished running."