- name: Upgrade Packages
  hosts: workers
  gather_facts: true
  become: true
  vars_files:
    - ../vaults/vault_ssh.yaml
    - ../vaults/vault_become.yaml
  tasks:

  - name: Upgrade all packages to the latest version
    dnf:
      name: "*"
      state: latest