- name: Upgrade Packages
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vaults/vault
  tasks:
    - name: Upgrade all packages to the latest version # noqa: package-latest
      ansible.builtin.dnf:
        name: "*"
        state: latest
