- name: Harden SSH configuration
  hosts: hosts
  become: true
  vars_files:
  - ../vaults/vault_ssh.yaml
  - ../vaults/vault_become.yaml
  tasks:
    - name: Ensure password authentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify:
        - Restart sshd

    - name: Ensure root login is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify:
        - Restart sshd

    - name: Ensure public key authentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
      notify:
        - Restart sshd

    - name: Ensure UsePAM is disabled (optional, depending on your security requirements)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?UsePAM'
        line: 'UsePAM no'
        state: present
      notify:
        - Restart sshd

    - name: Ensure SSH protocol version 2 is used
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Protocol'
        line: 'Protocol 2'
        state: present
      notify:
        - Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted