apiVersion: v1
kind: Service
metadata:
  name: netdata
  namespace: monitoring
  labels:
    app: netdata
spec:
  selector:
    app: netdata
  type: ClusterIP
  ports:
    - name: http
      port: 19999
      targetPort: 19999
      protocol: TCP
