apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      serviceAccountName: vmagent
      containers:
      - name: vmagent
        image: victoriametrics/vmagent:stable
        args:
          - '-promscrape.config=/etc/scrape/config.yaml'
          - '-remoteWrite.url=http://victoria-metrics:8428/api/v1/write'
        volumeMounts:
          - name: config-volume
            mountPath: /etc/scrape
      volumes:
        - name: config-volume
          configMap:
            name: vmagent-config
