apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmalert
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmalert
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmalert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmalert
subjects:
  - kind: ServiceAccount
    name: vmalert
    namespace: monitoring
