apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'mailpit'

    receivers:
      - name: 'mailpit'
        email_configs:
          - to: 'changeme@example.com'