name: Ansible

defaults:
  run:
    working-directory: ansible

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install ansible ansible-lint
          ansible-galaxy collection install ansible.posix

      - name: Create .vault_pass file
        run: echo "${{ secrets.VAULT_PASS }}" > .vault_pass

      - name: Run ansible-lint
        run: ansible-lint -s
