name: Ansible

on:
    pull_request:

jobs:
    ansible-lint:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: Install ansible and ansible-lint
              run: pip3 install ansible ansible-lint
            - name: Install ansible.posix collection
              run: ansible-galaxy collection install ansible.posix
            - name: Create .vault_pass file
              run: echo "${{ secrets.VAULT_PASS }}" > .vault_pass
            - name: Run ansible-lint
              run: ansible-lint ansible -s