name: OpenTofu

defaults:
  run:
    working-directory: opentofu

on:
    pull_request:

jobs:
    fmt:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: opentofu/setup-opentofu@v1
            - name: Run tofu fmt
              run: tofu fmt -check -write=false -diff
              continue-on-error: false