name: Tools

on:
  pull_request:

jobs:
  install: 
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install required tools
        run: |
          chmod +x ./scripts/install_tools.sh
          sudo ./scripts/install_tools.sh